---
title: "JGS_GLMM_Poisson_simulate_data"
author: "Justin Schuetz"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r}

library(tidyverse)
library(brms)
library(rethinking)
library(tidybayes)
library(rjags)

```

## Get data 

```{r}

tits <- read_table("tits.txt") %>%
  pivot_longer(cols = 5:31) %>%
  mutate(year = as.integer(str_sub(name, -4, -1)),
         type = str_sub(name, 1, -5)) %>%
  select(site, elevation, forest, year, value, type) %>%
  pivot_wider(id_cols = 1:4, values_from = "value", names_from = "type") %>%
  mutate(obs = as.character(obs),
         site_i = as.integer(as.factor(site)),
         year_j = year - (min(year) - 1)) %>%
  replace_na(list(obs = "272", first = 0)) %>%
  ungroup()
  

tits

```

## Plot site counts through time

```{r}


ggplot(tits, aes(year, y, color = site)) +
  geom_line() +
  guides(color = "none")


```

## Model simulated counts using brm

```{r}

m0_brm <- brm(y ~ 1,
             data = tits,
             family = poisson(),
             prior = prior(normal(0, 2), class = Intercept))


m0_brm


```


```{r}

tits_ret <- tits %>%
  select(y) %>%
  drop_na()

m0_ret <- ulam(
  
  alist(y ~ dpois(lambda),
        log(lambda) <- a,
        a ~ dnorm(0, 2)),
  data = tits_ret, 
  chains = 3,
  iter = 2000
  
)


precis(m0_ret)
traceplot(m0_ret, "a", alpha = 0.5)
trankplot(m0_ret, bg = col.alpha("black",0.15))
stancode(m0_ret)

```
## rjags

```{r}

C <- tits %>%
  dplyr::select(y, year, site) %>%
  pivot_wider(id_cols = year, names_from = site, values_from = y) %>%
  dplyr::select(-1) %>%
  as.matrix() %>%
  array(dim = c(9, 235))
  
n_years <- 9

n_sites <- 235

my_data <- list("C" = C, "n_years" = n_years, "n_sites" = n_sites)


sink("GLM0.txt")

cat("
    
    model {
    
      a ~ dnorm(0, 0.01)
    
      for (i in 1:n_years) {
    
        for (j in 1:n_sites) {
    
          C[i, j] ~ dpois(lambda[i, j])
          log(lambda[i, j]) <- (log.lambda[i, j])
          log.lambda[i, j] <- a
    
        }
    
      }
    
    }
    
    ", fill = TRUE)

sink()


inits <- function() list(a = runif(1, -10, 10))

model <- jags.model("GLM0.txt", 
                    data = my_data, 
                    inits = inits, 
                    n.chains = 4,
                    n.adapt = 1000)


update(model, n.iter = 1000)


samples <- coda.samples(model, 
                        variable.names = c("a"),
                        n.iter = 1000)


summary(samples)


plot(samples)


traceplot(samples)



```


```{r}

m1_brm <- brm(y ~ 0 + site,
             data = tits,
             family = poisson(),
             prior = prior(normal(0, 2), class = b),
             chains = 3)


m1_brm


```

```{r}

tits_ret <- tits %>%
  select(y, site_i) %>%
  drop_na(y) %>%
  arrange()

m1_ret <- ulam(
  
  alist(y ~ dpois(lambda),
        log(lambda) <- a[site_i],
        a[site_i] ~ dnorm(0, 2)),
  data = tits_ret, 
  chains = 3,
  iter = 2000
  
)


precis(m1_ret, depth = 2)
traceplot(m1_ret, "a", alpha = 0.5)
trankplot(m1_ret, bg = col.alpha("black",0.15))


```

## rjags

```{r}

C <- tits %>%
  dplyr::select(y, year, site) %>%
  pivot_wider(id_cols = year, names_from = site, values_from = y) %>%
  dplyr::select(-1) %>%
  as.matrix() %>%
  array(dim = c(9, 235))
  
n_years <- 9

n_sites <- 235

my_data <- list("C" = C, "n_years" = n_years, "n_sites" = n_sites)


sink("GLM1.txt")

cat("
    
    model {
    
      for (j in 1:n_sites) {
      
        a[j] ~ dnorm(0, 0.01)
      
      }
    
      for (i in 1:n_years) {
    
        for (j in 1:n_sites) {
    
          C[i, j] ~ dpois(lambda[i, j])
          log(lambda[i, j]) <- (log.lambda[i, j])
          log.lambda[i, j] <- a[j]
    
        }
    
      }
    
    }
    
    ", fill = TRUE)

sink()


inits <- function() list(a = runif(n_sites, -10, 10))

model <- jags.model("GLM1.txt", 
                    data = my_data, 
                    inits = inits, 
                    n.chains = 3,
                    n.adapt = 1000)


update(model, n.iter = 1000)


samples <- coda.samples(model, 
                        variable.names = c("a"),
                        n.iter = 1000)


summary(samples)


plot(samples)


traceplot(samples)



```

```{r}

# not sure how to deal with overparameterizatin in brms

m2_brm <- brm(y ~ 0 + site + year,
             data = tits,
             family = poisson(),
             prior = prior(normal(0, 2), class = b),
             chains = 3)


m2_brm


```


```{r}

# not sure how to deal with overparameterizatin in rethinking

tits_ret <- tits %>%
  select(y, site_i, year_j) %>%
  drop_na(y)

m2_ret <- ulam(
  
  alist(y ~ dpois(lambda),
        log(lambda) <- a[site_i] + e[year_j],
        a[site_i] ~ dnorm(0, 2),
        e[year_j] ~ dnorm(0, 2)),
  data = tits_ret, 
  chains = 3,
  iter = 2000
  
)


precis(m2_ret, depth = 2)
traceplot(m2_ret, alpha = 0.5)
trankplot(m2_ret, bg = col.alpha("black",0.15))


```

## rjags

```{r}

C <- tits %>%
  dplyr::select(y, year, site) %>%
  pivot_wider(id_cols = year, names_from = site, values_from = y) %>%
  dplyr::select(-1) %>%
  as.matrix() %>%
  array(dim = c(9, 235))
  
n_years <- 9

n_sites <- 235

my_data <- list("C" = C, "n_years" = n_years, "n_sites" = n_sites)


sink("GLM2.txt")

cat("
    
    model {
    
      for (j in 1:n_sites) {
      
        a[j] ~ dnorm(0, 0.01)
      
      }
    
      for (i in 2:n_years) {

        e[i] ~ dnorm(0, 0.01)
        
      }
      
      e[1] <- 0


      for (i in 1:n_years) {
    
        for (j in 1:n_sites) {
    
          C[i, j] ~ dpois(lambda[i, j])
          log(lambda[i, j]) <- (log.lambda[i, j])
          log.lambda[i, j] <- a[j] + e[i]
    
        }
    
      }
    
    }
    
    ", fill = TRUE)

sink()


inits <- function() list(a = runif(n_sites, -10, 10),
                         e = c(NA, runif(n_years - 1, -10, 10)))


model <- jags.model("GLM2.txt", 
                    data = my_data, 
                    inits = inits, 
                    n.chains = 3,
                    n.adapt = 1000)


update(model, n.iter = 1000)


samples <- coda.samples(model, 
                        variable.names = c("a", "e"),
                        n.iter = 1000)


summary(samples)


plot(samples)


traceplot(samples)



```

```{r}

tits_ret <- tits %>%
  select(y, year_j, site_i) %>%
  drop_na(y)

m3_ret <- ulam(
  
  alist(y ~ dpois(lambda),
        log(lambda) <- a[site_i],
        a[site_i] ~ dnorm(a_bar, a_sigma),
        a_bar ~ dnorm(0, 2),
        a_sigma ~ dexp(1)),
  data = tits_ret, 
  chains = 3,
  iter = 2000
  
)


precis(m3_ret, depth = 2)
traceplot(m3_ret, c("a_bar", "a_sigma"), alpha = 0.5)
trankplot(m3_ret, pars = c("a_bar", "a_sigma"))


```

## rjags

```{r}

C <- tits %>%
  dplyr::select(y, year, site) %>%
  pivot_wider(id_cols = year, names_from = site, values_from = y) %>%
  dplyr::select(-1) %>%
  as.matrix() %>%
  array(dim = c(9, 235))
  
n_years <- 9

n_sites <- 235

my_data <- list("C" = C, "n_years" = n_years, "n_sites" = n_sites)


sink("GLM3.txt")

cat("
    
    model {
    
      for (j in 1:n_sites) {
      
        a[j] ~ dnorm(a_bar, a_tau)
      
      }
    
      a_bar ~ dnorm(0, 0.01)
      a_tau <- 1 / (a_sigma * a_sigma)
      a_sigma ~ dunif(0, 3)


      for (i in 1:n_years) {
    
        for (j in 1:n_sites) {
    
          C[i, j] ~ dpois(lambda[i, j])
          log(lambda[i, j]) <- a[j] 
    
        }
    
      }
    
    }
    
    ", fill = TRUE)

sink()


inits <- function() list(a_bar = runif(1, -2, 3))


model <- jags.model("GLM3.txt", 
                    data = my_data, 
                    inits = inits, 
                    n.chains = 3,
                    n.adapt = 1000)


update(model, n.iter = 1000)


samples <- coda.samples(model, 
                        variable.names = c("a_bar", "a_sigma"),
                        n.iter = 1000)


summary(samples)


plot(samples)


traceplot(samples)



```


```{r}

m4_ret <- ulam(
  
  alist(y ~ dpois(lambda),
        log(lambda) <- a + y_re[year_j] + s_re[site_i],
        a ~ dnorm(0, 2),
        y_re[year_j] ~ dnorm(0, y_sigma),
        y_sigma ~ dexp(1),
        s_re[site_i] ~ dnorm(0, s_sigma),
        s_sigma ~ dexp(1)),
  data = tits_ret, 
  chains = 3,
  iter = 2000
  
)


precis(m4_ret, depth = 2)
traceplot(m4_ret, c("y_bar", "y_sigma"), alpha = 0.5)
trankplot(m4_ret, pars = c("y_bar", "y_sigma"))

```

## rjags

```{r}

C <- tits %>%
  dplyr::select(y, year, site) %>%
  pivot_wider(id_cols = year, names_from = site, values_from = y) %>%
  dplyr::select(-1) %>%
  as.matrix() %>%
  array(dim = c(9, 235))
  
n_years <- 9

n_sites <- 235

my_data <- list("C" = C, "n_years" = n_years, "n_sites" = n_sites)


sink("GLM4.txt")

cat("
    
    model {
    
      mu ~ dnorm(0, 0.01)
      
      for (j in 1:n_sites) {
      
        a[j] ~ dnorm(0, a_tau)
      
      }
    
      a_tau <- 1 / (a_sigma * a_sigma)
      a_sigma ~ dunif(0, 5)

    for (i in 1:n_years) {
      
        e[i] ~ dnorm(0, e_tau)
      
      }
    
      e_tau <- 1 / (e_sigma * e_sigma)
      e_sigma ~ dunif(0, 3)

      for (i in 1:n_years) {
    
        for (j in 1:n_sites) {
    
          C[i, j] ~ dpois(lambda[i, j])
          log(lambda[i, j]) <- mu + a[j] + e[i]
    
        }
    
      }
    
    }
    
    ", fill = TRUE)

sink()


inits <- function() list(mu = runif(1, 0, 4),
                         a = runif(n_sites, -2, 2),
                         e = runif(n_years, -2, 2))


model <- jags.model("GLM4.txt", 
                    data = my_data, 
                    inits = inits, 
                    n.chains = 3,
                    n.adapt = 5000)


update(model, n.iter = 5000)


samples <- coda.samples(model, 
                        variable.names = c("mu", "a", "e", "a_sigma", "e_sigma"),
                        n.iter = 5000,
                        thin = 5)


summary(samples)


plot(samples)


traceplot(samples)



```

## rjags

```{r}

C <- tits %>%
  dplyr::select(y, year, site) %>%
  pivot_wider(id_cols = year, names_from = site, values_from = y) %>%
  dplyr::select(-1) %>%
  as.matrix() %>%
  array(dim = c(9, 235))
  
n_years <- 9

n_sites <- 235

my_data <- list("C" = C, "n_years" = n_years, "n_sites" = n_sites)


sink("GLM4.txt")

cat("
    
    model {
    
      mu ~ dnorm(0, 0.01)
      
      for (j in 1:n_sites) {
      
        a[j] ~ dnorm(0, a_tau)
      
      }
    
      a_tau <- 1 / (a_sigma * a_sigma)
      a_sigma ~ dunif(0, 5)

    for (i in 1:n_years) {
      
        e[i] ~ dnorm(0, e_tau)
      
      }
    
      e_tau <- 1 / (e_sigma * e_sigma)
      e_sigma ~ dunif(0, 3)

      for (i in 1:n_years) {
    
        for (j in 1:n_sites) {
    
          C[i, j] ~ dpois(lambda[i, j])
          log(lambda[i, j]) <- mu + a[j] + e[i]
    
        }
    
      }
    
    }
    
    ", fill = TRUE)

sink()


inits <- function() list(mu = runif(1, 0, 4),
                         a = runif(n_sites, -2, 2),
                         e = runif(n_years, -2, 2))


model <- jags.model("GLM4.txt", 
                    data = my_data, 
                    inits = inits, 
                    n.chains = 3,
                    n.adapt = 5000)


update(model, n.iter = 5000)


samples <- coda.samples(model, 
                        variable.names = c("mu", "a", "e", "a_sigma", "e_sigma"),
                        n.iter = 5000,
                        thin = 5)


summary(samples)


plot(samples)


traceplot(samples)



```


```{r}

tits_ret <- tits %>%
  select(y, year_j, site_i, first) %>%
  drop_na(y) 


m7_ret <- ulam(
  
  alist(y ~ dpois(lambda),
        log(lambda) <- a + y_re[year_j] + s_re[site_i] + b1 * first,
        a ~ dnorm(0, 2),
        b1 ~ dnorm(0, 1),
        y_re[year_j] ~ dnorm(0, y_sigma),
        y_sigma ~ dexp(1),
        s_re[site_i] ~ dnorm(0, s_sigma),
        s_sigma ~ dexp(1)),
  data = tits_ret, 
  chains = 3,
  iter = 2000
  
)


precis(m7_ret, depth = 2)
traceplot(m5_ret, c("y_bar", "y_sigma"), alpha = 0.5)
trankplot(m5_ret, pars = c("y_bar", "y_sigma"))

```

