---
title: "JGS_GLM_Poisson_simulate_data"
author: "Justin Schuetz"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r}

library(tidyverse)
library(brms)
library(rethinking)
library(tidybayes)

```

## Simulate count data 

```{r}

# simulation

simData <- function(n = 40,
                    alpha = 3.5576,
                    beta1 = -0.0912,
                    beta2 = 0.0091,
                    beta3 = -0.00014){


  data <- tibble(year = 1:n,
                 yr = (year - mean(year)) / sd(year),
                 yr2 = yr^2,
                 yr3 = yr^3) %>%
    mutate(alpha = alpha,
           beta1 = beta1,
           beta2 = beta2,
           beta3 = beta3,
           log_expected_count = alpha + beta1 * year + beta2 * year^2 + beta3 * year^3,
           expected_count = exp(log_expected_count),
           C = rpois(n = n, lambda = expected_count))


  return(data)

}


data <- simData()

```

## Plot simulated counts

```{r}

ggplot(data, aes(year, C)) +
  geom_path()

```

## Model simulated counts using brm

```{r}

m_brm <- brm(C ~ 1 + yr + yr2 + yr3,
             data = data,
             family = poisson(link = "log"))


m_brm


```

```{r}

stancode(m_brm$fit)

```


```{r}

preds <- data %>%
  add_epred_draws(m_brm)


ggplot(preds, aes(year, .epred)) +
  stat_lineribbon(alpha = 0.25, fill = "red") +
  geom_line(aes(year, C))

```

## jags

```{r}

poisson_data <- list("C" = data$C,
                     "year" = data$yr,
                     "N" = 40)


sink("GLM_poisson_JGS.txt")

cat("

model {
    
  # priors
    
  alpha ~ dunif(-20, 20)
  beta1 ~ dunif(-10, 10)
  beta2 ~ dunif(-10, 10)
  beta3 ~ dunif(-10, 10)
    
  # likelihood
    
  for(i in 1:N) {
    
    C[i] ~ dpois(lambda[i])
    log(lambda[i]) <- log.lambda[i]
    log.lambda[i] <- alpha + beta1 * year[i] + beta2 * pow(year[i], 2) + beta3 * pow(year[i], 3)
      
  }
    
}", 

fill = TRUE)

sink()
    

poisson_inits <- function() list("alpha" = runif(1, -2, 2), 
                                 "beta1" = runif(1, -3, 3), 
                                 "beta2" = runif(1, -3, 3), 
                                 "beta3" = runif(1, -3, 3))


model <- jags.model("GLM_poisson_JGS.txt", 
                    data = poisson_data, 
                    inits = poisson_inits, 
                    n.chains = 4,
                    n.adapt = 2000)


update(model, n.iter = 1000)


samples <- coda.samples(model, 
                        variable.names = c("alpha", "beta1", "beta2", "beta3", "lambda"),
                        n.iter = 1000)


summary(samples)


plot(samples)


preds <- samples[[2]][ , 5:44] %>%
  data.frame() %>%
  pivot_longer(1:40) %>%
  mutate(year = as.integer(str_remove(name, "lambda.")))


ggplot(preds, aes(year, value)) +
  stat_lineribbon(alpha = 0.25, fill = "red") +
  geom_line(data = data, aes(year, C))

```


```{r}

m_ret <- ulam(
  
  alist(C ~ dpois(lambda),
        log(lambda) <- a + b1 * yr + b2 * yr2 + b3 * yr3,
        a ~ dnorm(0, 5),
        b1 ~ dnorm(0, 2),
        b2 ~ dnorm(0, 2),
        b3 ~ dnorm(0, 2)),
  data = data, 
  chains = 2,
  iter = 1000
  
)

m_ret
precis(m_ret)
traceplot(m_ret)

```

```{r}

m_ret2 <- map2stan(
  
  alist(C ~ dpois(lambda),
        log(lambda) <- a + b1 * yr + b2 * yr2 + b3 * yr3,
        a ~ dnorm(0, 5),
        b1 ~ dnorm(0, 2),
        b2 ~ dnorm(0, 2),
        b3 ~ dnorm(0, 2)),
  data = data
  
)

summary(m_ret2)
stancode(m_ret2)

```

```{r}

data_real <- read_rdump("GLM_Poisson.data.R")

data <- tibble(yr = data_real$year,
               yr2 = yr^2,
               yr3 = yr^3,
               C = data_real$C)

m_per <- ulam(
  
  alist(C ~ dpois(lambda),
        log(lambda) <- a + b1 * yr + b2 * yr2 + b3 * yr3,
        a ~ dnorm(0, 5),
        b1 ~ dnorm(0, 2),
        b2 ~ dnorm(0, 2),
        b3 ~ dnorm(0, 2)),
  data = data, 
  chains = 2,
  iter = 1000
  
)

m_per
precis(m_per)
traceplot(m_per)

post <- extract.samples(m_per, n = 1000)

pr <- link(m_per) 


```

## Model nestlings

```{r}

data_real <- read_rdump("GLM_Binomial.data.R")

data <- tibble(yr = data_real$year,
               yr2 = yr^2,
               yr3 = yr^3,
               C = data_real$C)

m_eye <- ulam(
  
  alist(C ~ dpois(lambda),
        log(lambda) <- a + b1 * yr + b2 * yr2 + b3 * yr3,
        a ~ dnorm(0, 5),
        b1 ~ dnorm(0, 2),
        b2 ~ dnorm(0, 2),
        b3 ~ dnorm(0, 2)),
  data = data, 
  chains = 2,
  iter = 1000
  
)

m_eye
precis(m_eye)
traceplot(m_eye)

pr <- link(m_per) %>%
  data.frame() %>%
  pivot_longer(1:40) %>%
  mutate(name = as.integer(str_remove(name, "X")))


ggplot(pr, aes(name, value)) +
  stat_lineribbon(alpha = 0.25, fill = "red")


```

